apiVersion: v1
kind: Service
metadata:
  name: golang-service
  labels: 
    app: golang
spec:
  type: ClusterIP
  selector:
    app: golang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

