apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  labels:
    app: golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang 
        image:  byisrar/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 80 
